name: myapp-devcontainer

services:
  gcc:
    build:
      context: '..'
      args:
        # these just need to be set, dev containers will patch uid&gid
        REMOTE_UID: 1001
        REMOTE_GID: 1001
        REMOTE_USER: mybcp

    # if you will use a ptrace-based debugger like C++, Go, and Rust.
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    volumes:
      - '../:/usr/mybcp/:rw'
      - '../.conan2_docker:/home/mybcp/.conan2:rw'

    environment:
      DOCKER: 'devcontainer'

    # keep container running
    entrypoint: sleep infinity
    stdin_open: true
    tty: true

